### ISSUE TITLE
code for train and eval part

### ISSUE THREAD

**Issue by jane-pyc** [caio-freitas/GraphARM#3]
Thank you for sharing! Can you please provide the code for the eval code? 
The current train code seems to provide only the model training part but not any metrics calculation process.

**Comment by caio-freitas** [comment]
The current project doesn't yet feature the metrics for evaluation. As the algorithm was originally developed to another application, the validation and evaluation metrics for the ZINC dataset weren't implemented here.

I'll open a new issue to implement these, so that we have that as next steps in the project.

**Comment by caio-freitas** [comment]
Described in #4
